name: sharding-repl-cache

services:
  configsvr:
    container_name: configsvr
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configrs --port 27019 --dbpath /data/db --bind_ip_all
    volumes:
      - configsvr_data:/data/db
    ports:
      - "27019:27019"
    networks:
      - app-network

  # ---------------------
  shard1_p:
    container_name: shard1_p
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1_r --port 27018 --dbpath /data/db --bind_ip_all
    volumes:
      - shard1_p_data:/data/db
    ports:
      - "27018:27018"
    networks:
      - app-network

  shard1_s1:
    container_name: shard1_s1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1_r --port 27018 --dbpath /data/db --bind_ip_all
    volumes:
      - shard1_s1_data:/data/db
    ports:
      - "27118:27018"
    networks:
      - app-network

  shard1_s2:
    container_name: shard1_s2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1_r --port 27018 --dbpath /data/db --bind_ip_all
    volumes:
      - shard1_s2_data:/data/db
    ports:
      - "27218:27018"
    networks:
      - app-network


  shard2_p:
    container_name: shard2_p
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2_r --port 27020 --dbpath /data/db --bind_ip_all
    volumes:
      - shard2_p_data:/data/db
    ports:
      - "27020:27020"
    networks:
      - app-network

  shard2_s1:
    container_name: shard2_s1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2_r --port 27020 --dbpath /data/db --bind_ip_all
    volumes:
      - shard2_s1_data:/data/db
    ports:
      - "27120:27020"
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
    networks:
      - app-network

  shard2_s2:
    container_name: shard2_s2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2_r --port 27020 --dbpath /data/db --bind_ip_all
    volumes:
      - shard2_s2_data:/data/db
    ports:
      - "27220:27020"
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
    networks:
      - app-network

  # -----------------------------------------------


  mongos:
    container_name: mongos
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongos --configdb configrs/configsvr:27019 --port 27017 --bind_ip_all
    depends_on:
      - configsvr
      - shard1_p
      - shard1_s1
      - shard1_s2
      - shard2_p
      - shard2_s1
      - shard2_s2
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
      - redis
    ports:
      - 8080:8080
    environment:
      REDIS_URL: "redis://redis:6379"
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      - app-network

volumes:
  configsvr_data:
  shard1_p_data:
  shard1_s1_data:
  shard1_s2_data:
  shard2_p_data:
  shard2_s1_data:
  shard2_s2_data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16
